# Homework 1: Data Reading & Manipulation

In this homework, you will practice:
1. Reading data from CSV files and APIs
2. Data manipulation techniques covered in Week 2

# Section 1: Reading Data

## 1.1 Reading CSV Files

##### IMPORTANT: We will read data from the `data/hw/` folder so you need to remember to go back two folders to access data

In [74]:
#IMPORT PANDAS TOOLS
import pandas as pd
pd.read_csv("../../data/hw/democracy_gdp.csv")
df= pd.read_csv("../../data/hw/democracy_gdp.csv")
df

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.650
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.650
2,AFG,1992,0.134,NaN,NaN,0.645,0.736,0.028,0.071,-1.650
3,AFG,1993,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.650
4,AFG,1994,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.650
...,...,...,...,...,...,...,...,...,...,...
5595,VNM,2020,0.044,NaN,NaN,0.489,0.373,0.495,0.206,1.255
5596,VNM,2021,0.042,NaN,NaN,0.517,0.390,0.526,0.177,1.977
5597,VNM,2022,0.025,NaN,NaN,0.517,0.372,0.531,0.186,1.977
5598,VNM,2023,0.021,NaN,NaN,0.517,0.364,0.513,0.187,1.571
5599,VNM,2024,0.021,NaN,NaN,0.477,0.364,0.514,0.176,1.963

### 1.1.1 GDP and Democracy Data

Load the `democracy_gdp.csv` file.

In [75]:
democracy_gdp_filepath = "../../data/hw/democracy_gdp.csv"
democracy_gdp = pd.read_csv(democracy_gdp_filepath)
democracy_gdp.head(4)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65
2,AFG,1992,0.134,NaN,NaN,0.645,0.736,0.028,0.071,-1.65
3,AFG,1993,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.65

### 1.1.2 Green house gas (GHG) Emissions Data

Load the `ghg.csv` file.

In [76]:
ghg_file_path = "../../data/hw/ghg.csv"
ghg = pd.read_csv(ghg_file_path)
ghg.tail(3)

            Country  year     emissions
11445  GLOBAL TOTAL  2021  51568.250032
11446  GLOBAL TOTAL  2022  51968.471601
11447  GLOBAL TOTAL  2023  52962.900859

## 1.2 Reading Data from an API

YOU MUST RUN THE NEXT CELL TO DOWNLOAD GDP AND POPULATION DATA

In [77]:
import requests
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    df = pd.read_xml(io.BytesIO(response.content))
    return df

### 1.2.1 Download GDP Data (1990-2026)

Download GDP per capita data for a different set of countries than those in the CSV files.

In [78]:
gdp_data = download_worldbank(
    indicator='NY.GDP.PCAP.CD',
    date_start= 1990,
    date_end= 2026,
    countries= ['USA', 'MEX', 'FRA']
)
gdp_data.head(2)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),France,FRA,2025,NaN,NaN,NaN,1
1,GDP per capita (current US$),France,FRA,2024,46103.084086,NaN,NaN,1

### 1.2.2 Download Population Data (1990-2026)

Download population data for the same countries.

In [79]:
population_indicator ='SP.POP.TOTL'
countries= ['USA', 'MEX', 'FRA']



country_list = [
    "USA",  # United States of America
    "CAN",  # Canada
    "MEX",  # Mexico
    "GBR",  # United Kingdom of Great Britain and Northern Ireland
    "FRA",  # France
    "DEU",  # Germany (Deutschland)
    "JPN",  # Japan
    "AUS"   # Australia
]

pop_data = download_worldbank(
    indicator=population_indicator,
    countries=country_list,
    date_start=1990,
    date_end=2026
)
pop_data.tail(3)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
285,"Population, total",United States,USA,1992,256514000.0,NaN,NaN,0
286,"Population, total",United States,USA,1991,252981000.0,NaN,NaN,0
287,"Population, total",United States,USA,1990,249623000.0,NaN,NaN,0

# Section 2: Data Manipulation

Now let's practice the data manipulation techniques from Week 2.

## 2.1 Select Columns

Select specific columns from the democracy_gdp dataset.

In [ ]:
df.country.unique()

array(['AFG', 'ARM', 'AZE', 'Asia (avg)', 'BGD', 'BTN', 'CHN', 'GEO',
       'HKG', 'IDN', 'IND', 'JPN', 'KAZ', 'KGZ', 'KHM', 'KOR', 'LAO',
       'LKA', 'MDV', 'MMR', 'MNG', 'MYS', 'NPL', 'PAK', 'PHL', 'PRK',
       'SGP', 'THA', 'TJK', 'TKM', 'TLS', 'TWN', 'UZB', 'VNM'],
      dtype=object)

## 2.2 Filter Rows

Filter rows based on conditions.

In [ ]:
df.year.unique()

array([1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000,
       2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,
       2023, 2024])

In [ ]:
# Filter using query

df.query("year == 2020")

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
30,AFG,2020,0.566000,NaN,NaN,0.818000,0.849000,0.161000,0.613000,-0.67300
65,ARM,2020,0.869000,NaN,NaN,0.264000,0.295000,0.901000,0.845000,1.94400
100,AZE,2020,0.290000,NaN,NaN,0.906000,0.938000,0.080000,0.207000,1.66700
135,Asia (avg),2020,0.531091,9987.530594,-3.98125,0.536182,0.552121,0.471364,0.497818,0.89997
170,BGD,2020,0.456000,NaN,NaN,0.916000,0.838000,0.158000,0.232000,-0.89000
...,...,...,...,...,...,...,...,...,...,...
5271,TWN,2020,0.901000,28727.743000,3.40000,0.167000,0.059000,0.942000,0.881000,2.73100
5272,TWN,2020,0.901000,28727.743000,3.40000,0.167000,0.059000,0.942000,0.881000,2.73100
5273,TWN,2020,0.901000,28727.743000,3.40000,0.167000,0.059000,0.942000,0.881000,2.73100
5560,UZB,2020,0.138000,NaN,NaN,0.842000,0.708000,0.237000,0.255000,0.95500
5595,VNM,2020,0.044000,NaN,NaN,0.489000,0.373000,0.495000,0.206000,1.25500

## 2.3 Multiple Conditions

Filter using multiple conditions.

In [156]:
# Filter with multiple conditions

df.query("country == ['KOR', 'JPN']")

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
385,JPN,1990,0.905,NaN,NaN,0.048,0.108,0.921,0.934,1.809
386,JPN,1991,0.904,NaN,NaN,0.048,0.108,0.921,0.934,1.809
387,JPN,1992,0.904,NaN,NaN,0.048,0.108,0.921,0.934,1.809
388,JPN,1993,0.905,NaN,NaN,0.048,0.108,0.921,0.934,1.809
389,JPN,1994,0.905,NaN,NaN,0.048,0.100,0.922,0.934,1.809
...,...,...,...,...,...,...,...,...,...,...
2760,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2761,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2762,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2763,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2764,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535

In [ ]:
#filter with multiple conditions take 2 

df.query("country == 'JPN & v2x_pubcorr'")
#it ran but nothing is showing... did i do this right?

Empty DataFrame
Columns: [country, year, v2x_frassoc_thick, NGDPDPC, NGDP_RPCH, v2x_pubcorr, v2xnp_regcorr, v2xel_frefair, v2x_freexp, v2elembcap]
Index: []

In [157]:
#take 3
democracy_gdp[(democracy_gdp['country'] == 'KOR') & (democracy_gdp['year'] == 2024)]

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
2701,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2702,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2703,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2704,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2705,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
...,...,...,...,...,...,...,...,...,...,...
2760,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2761,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2762,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2763,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2764,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535

## 2.4 Filter in a List

Filter rows where column value is in a list.

In [148]:
# Filter Multiple and show unique countries
# You can either do one or two lines

df.query("country in ['TWN', 'VNM']")
df.query("country in ['JPN', 'KOR']")

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
385,JPN,1990,0.905,NaN,NaN,0.048,0.108,0.921,0.934,1.809
386,JPN,1991,0.904,NaN,NaN,0.048,0.108,0.921,0.934,1.809
387,JPN,1992,0.904,NaN,NaN,0.048,0.108,0.921,0.934,1.809
388,JPN,1993,0.905,NaN,NaN,0.048,0.108,0.921,0.934,1.809
389,JPN,1994,0.905,NaN,NaN,0.048,0.100,0.922,0.934,1.809
...,...,...,...,...,...,...,...,...,...,...
2760,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2761,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2762,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2763,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2764,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535

## 2.5 Select Rows and Columns

Combine row filtering with column selection.

In [133]:
def basics(data):
    print('Head')
    print(data.head(2))
    print('')
    print('Tail')
    print(data.tail(2))
    print('')
    print('Columns')
    print(data.columns[:3])
    print('')
    print('Info')
    print(data.info())

basics(df)

Head
  country  year  v2x_frassoc_thick  NGDPDPC  NGDP_RPCH  v2x_pubcorr  \
0     AFG  1990              0.063      NaN        NaN        0.556
1     AFG  1991              0.068      NaN        NaN        0.556

   v2xnp_regcorr  v2xel_frefair  v2x_freexp  v2elembcap
0          0.538          0.069       0.085       -1.65
1          0.538          0.069       0.074       -1.65

Tail
     country  year  v2x_frassoc_thick  NGDPDPC  NGDP_RPCH  v2x_pubcorr  \
5598     VNM  2023              0.021      NaN        NaN        0.517
5599     VNM  2024              0.021      NaN        NaN        0.477

      v2xnp_regcorr  v2xel_frefair  v2x_freexp  v2elembcap
5598          0.364          0.513       0.187       1.571
5599          0.364          0.514       0.176       1.963

Columns
Index(['country', 'year', 'v2x_frassoc_thick'], dtype='object')

Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5600 entries, 0 to 5599
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   country            5600 non-null   object
 1   year               5600 non-null   int64
 2   v2x_frassoc_thick  5600 non-null   float64
 3   NGDPDPC            4515 non-null   float64
 4   NGDP_RPCH          4515 non-null   float64
 5   v2x_pubcorr        5589 non-null   float64
 6   v2xnp_regcorr      5589 non-null   float64
 7   v2xel_frefair      5600 non-null   float64
 8   v2x_freexp         5600 non-null   float64
 9   v2elembcap         5600 non-null   float64
dtypes: float64(8), int64(1), object(1)
memory usage: 437.6+ KB
None

In [ ]:
# Filter rows and select columns

democracy_gdp.loc[(democracy_gdp['country'] == 'JPN') & (democracy_gdp['year'] >= 2022), ['country', 'year', 'NGDPDPC', 'v2x_pubcorr']]

    country  year  NGDPDPC  v2x_pubcorr
417     JPN  2022      NaN        0.037
418     JPN  2023      NaN        0.037
419     JPN  2024      NaN        0.037

## 2.6 Rename Columns

Rename columns in the dataframe.

In [139]:
# Before rename
democracy_gdp.head(2)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65

In [141]:
# Rename using rename with axis parameter
rename_dictionary = {"v2x_frassoc_thick : codingishard"}
df.rename({"v2x_frassoc_thick" : "codingishard"}, axis=1).head(2)

,country,year,codingishard,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65