# Homework 1: Data Reading & Manipulation

In this homework, you will practice:
1. Reading data from CSV files and APIs
2. Data manipulation techniques covered in Week 2

# Section 1: Reading Data

## 1.1 Reading CSV Files

##### IMPORTANT: We will read data from the `data/hw/` folder so you need to remember to go back two folders to access data

In [5]:
#IMPORT PANDAS TOOLS
import pandas as pd

# More changes

### 1.1.1 GDP and Democracy Data

Load the `democracy_gdp.csv` file.

In [12]:
democracy_gdp = pd.read_csv("/Users/hannahwu/Documents/GitHub/datascience-publicpolicy-2026/data/hw/hw_3/data_gpr_daily_recent.csv")
democracy_gdp.head(4)

,DAY,N10D,GPRD,GPRD_ACT,GPRD_THREAT,date,GPRD_MA30,GPRD_MA7,event,var_name,var_label
0,19850101,216,230.04,275.20,153.03,1/1/1985,230.04,230.04,NaN,DAY,DAY
1,19850102,315,115.68,146.77,87.44,1/2/1985,172.86,172.86,NaN,N10D,"Number of articles (10 recent newspapers, 1985-)"
2,19850103,374,97.43,158.94,29.46,1/3/1985,147.71,147.71,NaN,GPRD,Daily GPR (Index: 1985:2019=100)
3,19850104,421,157.37,156.88,157.03,1/4/1985,150.13,150.13,NaN,GPRD_ACT,Daily GPR Acts (Index: 1985:2019=100)

### 1.1.2 Green house gas (GHG) Emissions Data

Load the `ghg.csv` file.

In [13]:
ghg_file_path = "/Users/hannahwu/Documents/GitHub/datascience-publicpolicy-2026/data/hw/ghg.csv"
ghg = pd.read_csv(ghg_file_path)
ghg.tail(3)

            Country  year     emissions
11445  GLOBAL TOTAL  2021  51568.250032
11446  GLOBAL TOTAL  2022  51968.471601
11447  GLOBAL TOTAL  2023  52962.900859

## 1.2 Reading Data from an API

YOU MUST RUN THE NEXT CELL TO DOWNLOAD GDP AND POPULATION DATA

In [14]:
import requests
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    df = pd.read_xml(io.BytesIO(response.content))
    return df

### 1.2.1 Download GDP Data (1990-2026)

Download GDP per capita data for a different set of countries than those in the CSV files.

In [22]:
gdp_data = download_worldbank(
    indicator='NY.GDP.PCAP.CD',
    date_start= 1990,
    date_end= 2026,
    countries= ['USA', 'CAN', 'MEX', 'GBR', 'FRA', 'DEU', 'JPN', 'AUS']
)
gdp_data.head(2)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),Australia,AUS,2025,NaN,NaN,NaN,1
1,GDP per capita (current US$),Australia,AUS,2024,64603.985631,NaN,NaN,1

### 1.2.2 Download Population Data (1990-2026)

Download population data for the same countries.

In [17]:
population_indicator = "SP.POP.TOTL"



country_list = [
    "USA",  # United States of America
    "CAN",  # Canada
    "MEX",  # Mexico
    "GBR",  # United Kingdom of Great Britain and Northern Ireland
    "FRA",  # France
    "DEU",  # Germany (Deutschland)
    "JPN",  # Japan
    "AUS"   # Australia
]

pop_data = download_worldbank(
    indicator=population_indicator,
    countries=country_list,
    date_start=1990,
    date_end=2026
)
pop_data.tail(3)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
285,"Population, total",United States,USA,1992,256514000.0,NaN,NaN,0
286,"Population, total",United States,USA,1991,252981000.0,NaN,NaN,0
287,"Population, total",United States,USA,1990,249623000.0,NaN,NaN,0

# Section 2: Data Manipulation

Now let's practice the data manipulation techniques from Week 2.

## 2.1 Select Columns

Select specific columns from the democracy_gdp dataset.

In [23]:
gdp_data["country"].head(5)

0    Australia
1    Australia
2    Australia
3    Australia
4    Australia
Name: country, dtype: object

## 2.2 Filter Rows

Filter rows based on conditions.

In [24]:
# Show unique values in a column
gdp_data["country"].unique()

array(['Australia', 'Canada', 'Germany', 'France', 'United Kingdom',
       'Japan', 'Mexico', 'United States'], dtype=object)

In [26]:
# Filter using query

gdp_data.query('country == "Japan"').head(3)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
180,GDP per capita (current US$),Japan,JPN,2025,NaN,NaN,NaN,1
181,GDP per capita (current US$),Japan,JPN,2024,32487.077805,NaN,NaN,1
182,GDP per capita (current US$),Japan,JPN,2023,33836.175627,NaN,NaN,1

## 2.3 Multiple Conditions

Filter using multiple conditions.

In [27]:
# Filter with multiple conditions

#YOUR CODE HERE
gdp_data.query('country == "Japan" & date == 2024')

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
181,GDP per capita (current US$),Japan,JPN,2024,32487.077805,NaN,NaN,1

## 2.4 Filter in a List

Filter rows where column value is in a list.

In [29]:
# Filter Multiple and show unique countries
# You can either do one or two lines

gdp_data.query('country in ["Japan", "USA"]').head(3)
#YOUR CODE HERE

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
180,GDP per capita (current US$),Japan,JPN,2025,NaN,NaN,NaN,1
181,GDP per capita (current US$),Japan,JPN,2024,32487.077805,NaN,NaN,1
182,GDP per capita (current US$),Japan,JPN,2023,33836.175627,NaN,NaN,1

## 2.5 Select Rows and Columns

Combine row filtering with column selection.

In [32]:
# Filter rows and select columns
gdp_data.query('country == "Japan"')[['country','date','value','indicator']].tail(3)
#YOUR CODE HERE

    country  date         value                     indicator
213   Japan  1992  31992.790212  GDP per capita (current US$)
214   Japan  1991  29428.428904  GDP per capita (current US$)
215   Japan  1990  25801.395039  GDP per capita (current US$)

## 2.6 Rename Columns

Rename columns in the dataframe.

In [33]:
# Before rename
democracy_gdp.head(2)

,DAY,N10D,GPRD,GPRD_ACT,GPRD_THREAT,date,GPRD_MA30,GPRD_MA7,event,var_name,var_label
0,19850101,216,230.04,275.20,153.03,1/1/1985,230.04,230.04,NaN,DAY,DAY
1,19850102,315,115.68,146.77,87.44,1/2/1985,172.86,172.86,NaN,N10D,"Number of articles (10 recent newspapers, 1985-)"

In [42]:
# Rename using rename with axis parameter
gdp_data.rename({'value': 'GDP'}, axis=1)
gdp_data.head(2)
#YOUR CODE HERE

,indicator,country,countryiso3code,date,GDP,unit,obs_status,decimal
0,GDP per capita (current US$),Australia,AUS,2025,NaN,NaN,NaN,1
1,GDP per capita (current US$),Australia,AUS,2024,64603.985631,NaN,NaN,1