# Homework 1: Data Reading & Manipulation

In this homework, you will practice:
1. Reading data from CSV files and APIs
2. Data manipulation techniques covered in Week 2

# Section 1: Reading Data

## 1.1 Reading CSV Files

##### IMPORTANT: We will read data from the `data/hw/` folder so you need to remember to go back two folders to access data

In [7]:
#IMPORT PANDAS TOOLS
import pandas as pd

### 1.1.1 GDP and Democracy Data

Load the `democracy_gdp.csv` file.

In [8]:
democracy_gdp_filepath = "../../data/hw/democracy_gdp.csv"
democracy_gdp = pd.read_csv(democracy_gdp_filepath)
democracy_gdp.head(4)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65
2,AFG,1992,0.134,NaN,NaN,0.645,0.736,0.028,0.071,-1.65
3,AFG,1993,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.65

### 1.1.2 Green house gas (GHG) Emissions Data

Load the `ghg.csv` file.

In [9]:
ghg_file_path = "../../data/hw/ghg.csv"
ghg = pd.read_csv(ghg_file_path)
ghg.tail(4)

            Country  year     emissions
11444  GLOBAL TOTAL  2020  49327.538885
11445  GLOBAL TOTAL  2021  51568.250032
11446  GLOBAL TOTAL  2022  51968.471601
11447  GLOBAL TOTAL  2023  52962.900859

## 1.2 Reading Data from an API

YOU MUST RUN THE NEXT CELL TO DOWNLOAD GDP AND POPULATION DATA

In [10]:
import requests
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    df = pd.read_xml(io.BytesIO(response.content))
    return df

### 1.2.1 Download GDP Data (1990-2026)

Download GDP per capita data for a different set of countries than those in the CSV files.

In [11]:
gdp_data = download_worldbank(
    indicator='NY.GDP.PCAP.CD',
    date_start= 1990,
    date_end= 2026,
    countries= ['BRA', 'ZAF']
)
gdp_data.head(10)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),Brazil,BRA,2025,NaN,NaN,NaN,1
1,GDP per capita (current US$),Brazil,BRA,2024,10310.548878,NaN,NaN,1
2,GDP per capita (current US$),Brazil,BRA,2023,10377.589772,NaN,NaN,1
3,GDP per capita (current US$),Brazil,BRA,2022,9281.332821,NaN,NaN,1
4,GDP per capita (current US$),Brazil,BRA,2021,7972.536961,NaN,NaN,1
5,GDP per capita (current US$),Brazil,BRA,2020,7074.194075,NaN,NaN,1
6,GDP per capita (current US$),Brazil,BRA,2019,9029.833044,NaN,NaN,1
7,GDP per capita (current US$),Brazil,BRA,2018,9300.660729,NaN,NaN,1
8,GDP per capita (current US$),Brazil,BRA,2017,10080.507872,NaN,NaN,1
9,GDP per capita (current US$),Brazil,BRA,2016,8836.285460,NaN,NaN,1

### 1.2.2 Download Population Data (1990-2026)

Download population data for the same countries.

In [12]:
population_indicator = "SP.POP.TOTL"



country_list = [
    "USA",  # United States of America
    "CAN",  # Canada
    "MEX",  # Mexico
    "GBR",  # United Kingdom of Great Britain and Northern Ireland
    "FRA",  # France
    "DEU",  # Germany (Deutschland)
    "JPN",  # Japan
    "AUS"   # Australia
]

pop_data = download_worldbank(
    indicator=population_indicator,
    countries=country_list,
    date_start=1990,
    date_end=2026
)
pop_data.tail(3)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
285,"Population, total",United States,USA,1992,256514000.0,NaN,NaN,0
286,"Population, total",United States,USA,1991,252981000.0,NaN,NaN,0
287,"Population, total",United States,USA,1990,249623000.0,NaN,NaN,0

# Section 2: Data Manipulation

Now let's practice the data manipulation techniques from Week 2.

## 2.1 Select Columns

Select specific columns from the democracy_gdp dataset.

In [20]:
df = democracy_gdp
type(df)
df[['country', 'year', 'v2x_frassoc_thick']]

     country  year  v2x_frassoc_thick
0        AFG  1990              0.063
1        AFG  1991              0.068
2        AFG  1992              0.134
3        AFG  1993              0.159
4        AFG  1994              0.159
...      ...   ...                ...
5595     VNM  2020              0.044
5596     VNM  2021              0.042
5597     VNM  2022              0.025
5598     VNM  2023              0.021
5599     VNM  2024              0.021

[5600 rows x 3 columns]

## 2.2 Filter Rows

Filter rows based on conditions.

In [21]:
df.country.unique()

array(['AFG', 'ARM', 'AZE', 'Asia (avg)', 'BGD', 'BTN', 'CHN', 'GEO',
       'HKG', 'IDN', 'IND', 'JPN', 'KAZ', 'KGZ', 'KHM', 'KOR', 'LAO',
       'LKA', 'MDV', 'MMR', 'MNG', 'MYS', 'NPL', 'PAK', 'PHL', 'PRK',
       'SGP', 'THA', 'TJK', 'TKM', 'TLS', 'TWN', 'UZB', 'VNM'],
      dtype=object)

In [22]:
# Filter using query

df.query("year == 1990 and country == 'AFG'")

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65

## 2.3 Multiple Conditions

Filter using multiple conditions.

In [23]:
# Filter with multiple conditions

df.query("year == 1990 and country == 'AFG' or year == 1990 and country == 'IND'")

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.650
350,IND,1990,0.800,NaN,NaN,0.374,0.548,0.789,0.814,0.768

## 2.4 Filter in a List

Filter rows where column value is in a list.

In [24]:
# Filter Multiple and show unique countries
# You can either do one or two lines

df.query("year == 1990 and country == 'AFG' or year == 1990 and country == 'IND'")['country'].unique()

array(['AFG', 'IND'], dtype=object)

## 2.5 Select Rows and Columns

Combine row filtering with column selection.

In [25]:
# Filter rows and select columns

df.query("country in ['IND', 'AFG']")[['country', 'year', 'v2x_frassoc_thick']]

    country  year  v2x_frassoc_thick
0       AFG  1990              0.063
1       AFG  1991              0.068
2       AFG  1992              0.134
3       AFG  1993              0.159
4       AFG  1994              0.159
..      ...   ...                ...
380     IND  2020              0.662
381     IND  2021              0.662
382     IND  2022              0.627
383     IND  2023              0.600
384     IND  2024              0.593

[70 rows x 3 columns]

## 2.6 Rename Columns

Rename columns in the dataframe.

In [26]:
# Before rename
democracy_gdp.head(2)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65

In [27]:
# Rename using rename with axis parameter

rename_dictionary = {"year" : "TIME", "country" : "Nation"}

df.rename(rename_dictionary, axis=1).head(2)

,Nation,TIME,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65