# Homework 1: Data Reading & Manipulation

In this homework, you will practice:
1. Reading data from CSV files and APIs
2. Data manipulation techniques covered in Week 2

# Section 1: Reading Data

## 1.1 Reading CSV Files

##### IMPORTANT: We will read data from the `data/hw/` folder so you need to remember to go back two folders to access data

In [156]:
#IMPORT PANDAS TOOLS
import pandas as pd

In [ ]:
#Comment you can delete later this is just to have a change to show yayyyyyy

### 1.1.1 GDP and Democracy Data

Load the `democracy_gdp.csv` file.

In [157]:
democracy_gdp_filepath = "../../data/hw/democracy_gdp.csv"
democracy_gdp = pd.read_csv(democracy_gdp_filepath)
democracy_gdp.head(150)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.650
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.650
2,AFG,1992,0.134,NaN,NaN,0.645,0.736,0.028,0.071,-1.650
3,AFG,1993,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.650
4,AFG,1994,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.650
...,...,...,...,...,...,...,...,...,...,...
145,BGD,1995,0.739,NaN,NaN,0.898,0.732,0.526,0.688,-0.828
146,BGD,1996,0.744,NaN,NaN,0.936,0.656,0.534,0.623,-0.828
147,BGD,1997,0.759,NaN,NaN,0.936,0.656,0.534,0.623,-0.828
148,BGD,1998,0.759,NaN,NaN,0.936,0.656,0.534,0.623,-0.828
149,BGD,1999,0.759,NaN,NaN,0.936,0.656,0.534,0.623,-0.828

### 1.1.2 Green house gas (GHG) Emissions Data

Load the `ghg.csv` file.

In [158]:
ghg_file_path = "../../data/hw/ghg.csv"
ghg = pd.read_csv(ghg_file_path)
ghg.tail(3)

            Country  year     emissions
11445  GLOBAL TOTAL  2021  51568.250032
11446  GLOBAL TOTAL  2022  51968.471601
11447  GLOBAL TOTAL  2023  52962.900859

## 1.2 Reading Data from an API

YOU MUST RUN THE NEXT CELL TO DOWNLOAD GDP AND POPULATION DATA

In [159]:
import requests
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    df = pd.read_xml(io.BytesIO(response.content))
    return df

### 1.2.1 Download GDP Data (1990-2026)

Download GDP per capita data for a different set of countries than those in the CSV files.

In [160]:
gdp_data = download_worldbank(
    indicator='NY.GDP.PCAP.CD',
    date_start= 1990,
    date_end= 2026,
    countries= ['FRA','BRA','BOL']
)
gdp_data.head(75)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),Bolivia,BOL,2025,NaN,NaN,NaN,1
1,GDP per capita (current US$),Bolivia,BOL,2024,4421.166099,NaN,NaN,1
2,GDP per capita (current US$),Bolivia,BOL,2023,4274.708205,NaN,NaN,1
3,GDP per capita (current US$),Bolivia,BOL,2022,4219.461137,NaN,NaN,1
4,GDP per capita (current US$),Bolivia,BOL,2021,4010.760537,NaN,NaN,1
...,...,...,...,...,...,...,...,...
70,GDP per capita (current US$),Brazil,BRA,1991,2258.104540,NaN,NaN,1
71,GDP per capita (current US$),Brazil,BRA,1990,2619.801411,NaN,NaN,1
72,GDP per capita (current US$),France,FRA,2025,NaN,NaN,NaN,1
73,GDP per capita (current US$),France,FRA,2024,46103.084086,NaN,NaN,1
74,GDP per capita (current US$),France,FRA,2023,44700.138418,NaN,NaN,1

### 1.2.2 Download Population Data (1990-2026)

Download population data for the same countries.

In [161]:
population_indicator = 'sp.pop.totl'

country_list = [
    "USA",  # United States of America
    "CAN",  # Canada
    "MEX",  # Mexico
    "GBR",  # United Kingdom of Great Britain and Northern Ireland
    "FRA",  # France
    "DEU",  # Germany (Deutschland)
    "JPN",  # Japan
    "AUS"   # Australia
]

pop_data = download_worldbank(
    indicator=population_indicator,
    countries=country_list,
    date_start=1990,
    date_end=2026
)
pop_data.tail(100)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
188,"Population, total",Japan,JPN,2017,126972000.0,NaN,NaN,0
189,"Population, total",Japan,JPN,2016,127076000.0,NaN,NaN,0
190,"Population, total",Japan,JPN,2015,127141000.0,NaN,NaN,0
191,"Population, total",Japan,JPN,2014,127276000.0,NaN,NaN,0
192,"Population, total",Japan,JPN,2013,127445000.0,NaN,NaN,0
...,...,...,...,...,...,...,...,...
283,"Population, total",United States,USA,1994,263126000.0,NaN,NaN,0
284,"Population, total",United States,USA,1993,259919000.0,NaN,NaN,0
285,"Population, total",United States,USA,1992,256514000.0,NaN,NaN,0
286,"Population, total",United States,USA,1991,252981000.0,NaN,NaN,0
287,"Population, total",United States,USA,1990,249623000.0,NaN,NaN,0

# Section 2: Data Manipulation

Now let's practice the data manipulation techniques from Week 2.

## 2.1 Select Columns

Select specific columns from the democracy_gdp dataset.

In [162]:
selected_columns = democracy_gdp [['country', 'year', 'v2xnp_regcorr']]
selected_columns.head(15)

   country  year  v2xnp_regcorr
0      AFG  1990          0.538
1      AFG  1991          0.538
2      AFG  1992          0.736
3      AFG  1993          0.909
4      AFG  1994          0.909
5      AFG  1995          0.912
6      AFG  1996          0.906
7      AFG  1997          0.806
8      AFG  1998          0.806
9      AFG  1999          0.806
10     AFG  2000          0.806
11     AFG  2001          0.806
12     AFG  2002          0.910
13     AFG  2003          0.910
14     AFG  2004          0.934

## 2.2 Filter Rows

Filter rows based on conditions.

In [163]:
# Show unique values in a column
democracy_gdp['country'].unique()

array(['AFG', 'ARM', 'AZE', 'Asia (avg)', 'BGD', 'BTN', 'CHN', 'GEO',
       'HKG', 'IDN', 'IND', 'JPN', 'KAZ', 'KGZ', 'KHM', 'KOR', 'LAO',
       'LKA', 'MDV', 'MMR', 'MNG', 'MYS', 'NPL', 'PAK', 'PHL', 'PRK',
       'SGP', 'THA', 'TJK', 'TKM', 'TLS', 'TWN', 'UZB', 'VNM'],
      dtype=object)

In [164]:
# Filter using query

democracy_gdp.query("country == ['GEO','ARM']")

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
35,ARM,1990,0.717,NaN,NaN,0.321,0.247,0.722,0.711,-0.326
36,ARM,1991,0.782,NaN,NaN,0.414,0.313,0.724,0.778,0.000
37,ARM,1992,0.788,NaN,NaN,0.414,0.348,0.741,0.771,0.000
38,ARM,1993,0.761,NaN,NaN,0.414,0.411,0.741,0.765,0.000
39,ARM,1994,0.741,NaN,NaN,0.414,0.411,0.741,0.734,0.000
...,...,...,...,...,...,...,...,...,...,...
275,GEO,2020,0.878,NaN,NaN,0.136,0.159,0.555,0.876,2.071
276,GEO,2021,0.854,NaN,NaN,0.128,0.197,0.549,0.867,2.071
277,GEO,2022,0.855,NaN,NaN,0.123,0.205,0.548,0.867,2.071
278,GEO,2023,0.808,NaN,NaN,0.123,0.207,0.553,0.832,2.071
279,GEO,2024,0.728,NaN,NaN,0.134,0.265,0.472,0.696,1.845

## 2.3 Multiple Conditions

Filter using multiple conditions.

In [165]:
# Filter with multiple conditi
democracy_gdp.query("country == ['GEO','ARM'] and year >=2015")

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
60,ARM,2015,0.676,NaN,NaN,0.710,0.856,0.191,0.644,0.972
61,ARM,2016,0.675,NaN,NaN,0.710,0.856,0.187,0.649,0.972
62,ARM,2017,0.717,NaN,NaN,0.680,0.818,0.274,0.665,1.054
63,ARM,2018,0.832,NaN,NaN,0.324,0.346,0.454,0.816,2.061
64,ARM,2019,0.872,NaN,NaN,0.199,0.268,0.921,0.852,2.061
65,ARM,2020,0.869,NaN,NaN,0.264,0.295,0.901,0.845,1.944
66,ARM,2021,0.876,NaN,NaN,0.264,0.337,0.813,0.797,2.239
67,ARM,2022,0.892,NaN,NaN,0.264,0.329,0.657,0.782,1.031
68,ARM,2023,0.887,NaN,NaN,0.323,0.368,0.677,0.721,1.447
69,ARM,2024,0.888,NaN,NaN,0.323,0.368,0.677,0.706,1.447
270,GEO,2015,0.854,NaN,NaN,0.097,0.140,0.648,0.906,1.343
271,GEO,2016,0.867,NaN,NaN,0.097,0.150,0.669,0.914,1.736
272,GEO,2017,0.893,NaN,NaN,0.104,0.145,0.654,0.910,1.950
273,GEO,2018,0.878,NaN,NaN,0.126,0.154,0.635,0.897,1.929
274,GEO,2019,0.864,NaN,NaN,0.126,0.160,0.571,0.894,2.071
275,GEO,2020,0.878,NaN,NaN,0.136,0.159,0.555,0.876,2.071
276,GEO,2021,0.854,NaN,NaN,0.128,0.197,0.549,0.867,2.071
277,GEO,2022,0.855,NaN,NaN,0.123,0.205,0.548,0.867,2.071
278,GEO,2023,0.808,NaN,NaN,0.123,0.207,0.553,0.832,2.071
279,GEO,2024,0.728,NaN,NaN,0.134,0.265,0.472,0.696,1.845

## 2.4 Filter in a List

Filter rows where column value is in a list.

In [166]:
# Filter Multiple and show unique countries
filtered = democracy_gdp[democracy_gdp['country'].isin(['JPN', 'KOR'])]
filtered.head(60)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
385,JPN,1990,0.905,NaN,NaN,0.048,0.108,0.921,0.934,1.809
386,JPN,1991,0.904,NaN,NaN,0.048,0.108,0.921,0.934,1.809
387,JPN,1992,0.904,NaN,NaN,0.048,0.108,0.921,0.934,1.809
388,JPN,1993,0.905,NaN,NaN,0.048,0.108,0.921,0.934,1.809
389,JPN,1994,0.905,NaN,NaN,0.048,0.100,0.922,0.934,1.809
390,JPN,1995,0.905,NaN,NaN,0.048,0.100,0.922,0.934,1.809
391,JPN,1996,0.905,NaN,NaN,0.048,0.100,0.922,0.934,1.809
392,JPN,1997,0.906,NaN,NaN,0.048,0.100,0.921,0.934,1.809
393,JPN,1998,0.906,NaN,NaN,0.037,0.100,0.921,0.934,1.809
394,JPN,1999,0.906,NaN,NaN,0.037,0.100,0.921,0.934,1.809
395,JPN,2000,0.904,NaN,NaN,0.037,0.100,0.921,0.934,1.809
396,JPN,2001,0.902,NaN,NaN,0.037,0.100,0.920,0.934,1.809
397,JPN,2002,0.902,NaN,NaN,0.037,0.100,0.920,0.934,1.809
398,JPN,2003,0.902,NaN,NaN,0.037,0.100,0.921,0.934,1.809
399,JPN,2004,0.905,NaN,NaN,0.037,0.100,0.923,0.934,1.809
400,JPN,2005,0.906,NaN,NaN,0.037,0.100,0.927,0.934,1.809
401,JPN,2006,0.908,NaN,NaN,0.037,0.100,0.934,0.934,1.809
402,JPN,2007,0.908,NaN,NaN,0.037,0.100,0.934,0.934,1.809
403,JPN,2008,0.909,NaN,NaN,0.037,0.100,0.934,0.934,1.973
404,JPN,2009,0.915,NaN,NaN,0.037,0.100,0.934,0.938,1.973
405,JPN,2010,0.915,NaN,NaN,0.037,0.100,0.933,0.938,1.816
406,JPN,2011,0.915,NaN,NaN,0.037,0.100,0.933,0.938,1.816
407,JPN,2012,0.907,NaN,NaN,0.037,0.100,0.933,0.936,1.816
408,JPN,2013,0.909,NaN,NaN,0.037,0.100,0.931,0.883,1.816
409,JPN,2014,0.909,NaN,NaN,0.037,0.100,0.931,0.883,1.816
410,JPN,2015,0.911,NaN,NaN,0.037,0.078,0.931,0.883,1.816
411,JPN,2016,0.911,NaN,NaN,0.037,0.116,0.931,0.883,1.816
412,JPN,2017,0.911,NaN,NaN,0.037,0.107,0.933,0.883,1.816
413,JPN,2018,0.933,NaN,NaN,0.037,0.107,0.946,0.874,2.009
414,JPN,2019,0.930,NaN,NaN,0.037,0.107,0.946,0.871,2.009
415,JPN,2020,0.930,NaN,NaN,0.037,0.107,0.943,0.876,1.919
416,JPN,2021,0.929,NaN,NaN,0.037,0.094,0.943,0.859,1.919
417,JPN,2022,0.927,NaN,NaN,0.037,0.094,0.938,0.865,1.919
418,JPN,2023,0.927,NaN,NaN,0.037,0.092,0.938,0.866,1.919
419,JPN,2024,0.927,NaN,NaN,0.037,0.092,0.934,0.865,1.676
525,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
526,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
527,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
528,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
529,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
530,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
531,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
532,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
533,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
534,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
535,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
536,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
537,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
538,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
539,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
540,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
541,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
542,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
543,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
544,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
545,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
546,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
547,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
548,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369
549,KOR,1990,0.782,6812.886,10.0,0.339,0.559,0.744,0.800,1.369

## 2.5 Select Rows and Columns

Combine row filtering with column selection.

In [167]:
# Filter rows and select columns
democracy_gdp.query("country == 'JPN'")[['country', 'year', 'NGDPDPC']]

    country  year  NGDPDPC
385     JPN  1990      NaN
386     JPN  1991      NaN
387     JPN  1992      NaN
388     JPN  1993      NaN
389     JPN  1994      NaN
390     JPN  1995      NaN
391     JPN  1996      NaN
392     JPN  1997      NaN
393     JPN  1998      NaN
394     JPN  1999      NaN
395     JPN  2000      NaN
396     JPN  2001      NaN
397     JPN  2002      NaN
398     JPN  2003      NaN
399     JPN  2004      NaN
400     JPN  2005      NaN
401     JPN  2006      NaN
402     JPN  2007      NaN
403     JPN  2008      NaN
404     JPN  2009      NaN
405     JPN  2010      NaN
406     JPN  2011      NaN
407     JPN  2012      NaN
408     JPN  2013      NaN
409     JPN  2014      NaN
410     JPN  2015      NaN
411     JPN  2016      NaN
412     JPN  2017      NaN
413     JPN  2018      NaN
414     JPN  2019      NaN
415     JPN  2020      NaN
416     JPN  2021      NaN
417     JPN  2022      NaN
418     JPN  2023      NaN
419     JPN  2024      NaN

## 2.6 Rename Columns

Rename columns in the dataframe.

In [168]:
# Before rename
democracy_gdp.head(2)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65

In [169]:
# Rename using rename with axis parameter

democracy_gdp = democracy_gdp.rename ({'NGDPDPC': 'gdp_per_capita',
'v2x_pubcorr': 'thisisnoteasy',
'NGDP_RPCH' : 'itis2amandIamsleepy'},
axis=1)

In [170]:
democracy_gdp.query("country == 'JPN'")[['country', 'year', 'gdp_per_capita', 'thisisnoteasy', 'itis2amandIamsleepy']]

    country  year  gdp_per_capita  thisisnoteasy  itis2amandIamsleepy
385     JPN  1990             NaN          0.048                  NaN
386     JPN  1991             NaN          0.048                  NaN
387     JPN  1992             NaN          0.048                  NaN
388     JPN  1993             NaN          0.048                  NaN
389     JPN  1994             NaN          0.048                  NaN
390     JPN  1995             NaN          0.048                  NaN
391     JPN  1996             NaN          0.048                  NaN
392     JPN  1997             NaN          0.048                  NaN
393     JPN  1998             NaN          0.037                  NaN
394     JPN  1999             NaN          0.037                  NaN
395     JPN  2000             NaN          0.037                  NaN
396     JPN  2001             NaN          0.037                  NaN
397     JPN  2002             NaN          0.037                  NaN
398     JPN  2003             NaN          0.037                  NaN
399     JPN  2004             NaN          0.037                  NaN
400     JPN  2005             NaN          0.037                  NaN
401     JPN  2006             NaN          0.037                  NaN
402     JPN  2007             NaN          0.037                  NaN
403     JPN  2008             NaN          0.037                  NaN
404     JPN  2009             NaN          0.037                  NaN
405     JPN  2010             NaN          0.037                  NaN
406     JPN  2011             NaN          0.037                  NaN
407     JPN  2012             NaN          0.037                  NaN
408     JPN  2013             NaN          0.037                  NaN
409     JPN  2014             NaN          0.037                  NaN
410     JPN  2015             NaN          0.037                  NaN
411     JPN  2016             NaN          0.037                  NaN
412     JPN  2017             NaN          0.037                  NaN
413     JPN  2018             NaN          0.037                  NaN
414     JPN  2019             NaN          0.037                  NaN
415     JPN  2020             NaN          0.037                  NaN
416     JPN  2021             NaN          0.037                  NaN
417     JPN  2022             NaN          0.037                  NaN
418     JPN  2023             NaN          0.037                  NaN
419     JPN  2024             NaN          0.037                  NaN