# Homework 1: Data Reading & Manipulation

In this homework, you will practice:
1. Reading data from CSV files and APIs
2. Data manipulation techniques covered in Week 2

# Section 1: Reading Data

## 1.1 Reading CSV Files

##### IMPORTANT: We will read data from the `data/hw/` folder so you need to remember to go back two folders to access data

In [1]:
#IMPORT PANDAS TOOLS
import pandas as pd

### 1.1.1 GDP and Democracy Data

Load the `democracy_gdp.csv` file.

In [2]:
democracy_gdp_filepath = "../../data/hw/democracy_gdp.csv"
democracy_gdp = pd.read_csv(democracy_gdp_filepath)
democracy_gdp.head(10)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65
2,AFG,1992,0.134,NaN,NaN,0.645,0.736,0.028,0.071,-1.65
3,AFG,1993,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.65
4,AFG,1994,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.65
5,AFG,1995,0.159,NaN,NaN,0.843,0.912,0.000,0.069,-1.65
6,AFG,1996,0.062,NaN,NaN,0.745,0.906,0.000,0.029,-1.65
7,AFG,1997,0.038,NaN,NaN,0.707,0.806,0.000,0.020,-1.65
8,AFG,1998,0.038,NaN,NaN,0.707,0.806,0.000,0.020,-1.65
9,AFG,1999,0.038,NaN,NaN,0.707,0.806,0.000,0.020,-1.65

### 1.1.2 Green house gas (GHG) Emissions Data

Load the `ghg.csv` file.

In [3]:
ghg_file_path = "../../data/hw/ghg.csv"
ghg = pd.read_csv(ghg_file_path)
ghg.tail(10)

            Country  year     emissions
11438  GLOBAL TOTAL  2014  48930.176837
11439  GLOBAL TOTAL  2015  48808.767176
11440  GLOBAL TOTAL  2016  49058.441256
11441  GLOBAL TOTAL  2017  49878.733809
11442  GLOBAL TOTAL  2018  51026.627449
11443  GLOBAL TOTAL  2019  51278.347920
11444  GLOBAL TOTAL  2020  49327.538885
11445  GLOBAL TOTAL  2021  51568.250032
11446  GLOBAL TOTAL  2022  51968.471601
11447  GLOBAL TOTAL  2023  52962.900859

## 1.2 Reading Data from an API

YOU MUST RUN THE NEXT CELL TO DOWNLOAD GDP AND POPULATION DATA

In [4]:
import requests
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    df = pd.read_xml(io.BytesIO(response.content))
    return df

### 1.2.1 Download GDP Data (1990-2026)

Download GDP per capita data for a different set of countries than those in the CSV files.

In [5]:
gdp_data = download_worldbank(
    indicator='NY.GDP.PCAP.CD',
    date_start= 1990,
    date_end= 2026,
    countries= [
        'ESP',
        'FRA',
        'DEU',
        'ITA',
    ]
)
gdp_data

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),Germany,DEU,2025,NaN,NaN,NaN,1
1,GDP per capita (current US$),Germany,DEU,2024,56103.732318,NaN,NaN,1
2,GDP per capita (current US$),Germany,DEU,2023,54776.766824,NaN,NaN,1
3,GDP per capita (current US$),Germany,DEU,2022,50506.517964,NaN,NaN,1
4,GDP per capita (current US$),Germany,DEU,2021,52349.245999,NaN,NaN,1
...,...,...,...,...,...,...,...,...
139,GDP per capita (current US$),Italy,ITA,1994,19382.200215,NaN,NaN,1
140,GDP per capita (current US$),Italy,ITA,1993,18781.952943,NaN,NaN,1
141,GDP per capita (current US$),Italy,ITA,1992,23297.046033,NaN,NaN,1
142,GDP per capita (current US$),Italy,ITA,1991,22007.135096,NaN,NaN,1
143,GDP per capita (current US$),Italy,ITA,1990,20873.783409,NaN,NaN,1

### 1.2.2 Download Population Data (1990-2026)

Download population data for the same countries.

In [7]:
population_indicator = 'SP.POP.TOTL'

country_list = [
    "ESP",  
    "FRA",  
    "DEU",  
    "ITA",  
]

pop_data = download_worldbank(
    indicator=population_indicator,
    countries=country_list,
    date_start=1990,
    date_end=2026
)
pop_data.tail(3)
pop_data

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"Population, total",Germany,DEU,2025,NaN,NaN,NaN,0
1,"Population, total",Germany,DEU,2024,83516593.0,NaN,NaN,0
2,"Population, total",Germany,DEU,2023,83287273.0,NaN,NaN,0
3,"Population, total",Germany,DEU,2022,83177813.0,NaN,NaN,0
4,"Population, total",Germany,DEU,2021,83196078.0,NaN,NaN,0
...,...,...,...,...,...,...,...,...
139,"Population, total",Italy,ITA,1994,56843400.0,NaN,NaN,0
140,"Population, total",Italy,ITA,1993,56831821.0,NaN,NaN,0
141,"Population, total",Italy,ITA,1992,56797087.0,NaN,NaN,0
142,"Population, total",Italy,ITA,1991,56758521.0,NaN,NaN,0
143,"Population, total",Italy,ITA,1990,56719240.0,NaN,NaN,0

# Section 2: Data Manipulation

Now let's practice the data manipulation techniques from Week 2.

## 2.1 Select Columns

Select specific columns from the democracy_gdp dataset.

In [8]:
gdp_data[['country','date','value']]

     country  date         value
0    Germany  2025           NaN
1    Germany  2024  56103.732318
2    Germany  2023  54776.766824
3    Germany  2022  50506.517964
4    Germany  2021  52349.245999
..       ...   ...           ...
139    Italy  1994  19382.200215
140    Italy  1993  18781.952943
141    Italy  1992  23297.046033
142    Italy  1991  22007.135096
143    Italy  1990  20873.783409

[144 rows x 3 columns]

## 2.2 Filter Rows

Filter rows based on conditions.

In [14]:
# Show unique values in a column
gdp_data.country.unique()

array(['Germany', 'Spain', 'France', 'Italy'], dtype=object)

In [11]:
gdp_data.date.unique()

array([2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015,
       2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004,
       2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993,
       1992, 1991, 1990])

In [13]:
gdp_data.countryiso3code.unique()

array(['DEU', 'ESP', 'FRA', 'ITA'], dtype=object)

In [15]:
# Filter using query

pop_data.query('countryiso3code == "ESP"')

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
36,"Population, total",Spain,ESP,2025,NaN,NaN,NaN,0
37,"Population, total",Spain,ESP,2024,48848840.0,NaN,NaN,0
38,"Population, total",Spain,ESP,2023,48352528.0,NaN,NaN,0
39,"Population, total",Spain,ESP,2022,47786102.0,NaN,NaN,0
40,"Population, total",Spain,ESP,2021,47443821.0,NaN,NaN,0
41,"Population, total",Spain,ESP,2020,47359424.0,NaN,NaN,0
42,"Population, total",Spain,ESP,2019,47118501.0,NaN,NaN,0
43,"Population, total",Spain,ESP,2018,46782011.0,NaN,NaN,0
44,"Population, total",Spain,ESP,2017,46571232.0,NaN,NaN,0
45,"Population, total",Spain,ESP,2016,46458139.0,NaN,NaN,0
46,"Population, total",Spain,ESP,2015,46422303.0,NaN,NaN,0
47,"Population, total",Spain,ESP,2014,46460733.0,NaN,NaN,0
48,"Population, total",Spain,ESP,2013,46604197.0,NaN,NaN,0
49,"Population, total",Spain,ESP,2012,46773055.0,NaN,NaN,0
50,"Population, total",Spain,ESP,2011,46742697.0,NaN,NaN,0
51,"Population, total",Spain,ESP,2010,46576897.0,NaN,NaN,0
52,"Population, total",Spain,ESP,2009,46362946.0,NaN,NaN,0
53,"Population, total",Spain,ESP,2008,45954106.0,NaN,NaN,0
54,"Population, total",Spain,ESP,2007,45226803.0,NaN,NaN,0
55,"Population, total",Spain,ESP,2006,44397319.0,NaN,NaN,0
56,"Population, total",Spain,ESP,2005,43653155.0,NaN,NaN,0
57,"Population, total",Spain,ESP,2004,42921895.0,NaN,NaN,0
58,"Population, total",Spain,ESP,2003,42187645.0,NaN,NaN,0
59,"Population, total",Spain,ESP,2002,41431558.0,NaN,NaN,0
60,"Population, total",Spain,ESP,2001,40850412.0,NaN,NaN,0
61,"Population, total",Spain,ESP,2000,40567864.0,NaN,NaN,0
62,"Population, total",Spain,ESP,1999,40386875.0,NaN,NaN,0
63,"Population, total",Spain,ESP,1998,40223509.0,NaN,NaN,0
64,"Population, total",Spain,ESP,1997,40057389.0,NaN,NaN,0
65,"Population, total",Spain,ESP,1996,39889852.0,NaN,NaN,0
66,"Population, total",Spain,ESP,1995,39724050.0,NaN,NaN,0
67,"Population, total",Spain,ESP,1994,39549108.0,NaN,NaN,0
68,"Population, total",Spain,ESP,1993,39361262.0,NaN,NaN,0
69,"Population, total",Spain,ESP,1992,39157685.0,NaN,NaN,0
70,"Population, total",Spain,ESP,1991,38966376.0,NaN,NaN,0
71,"Population, total",Spain,ESP,1990,38867322.0,NaN,NaN,0

## 2.3 Multiple Conditions

Filter using multiple conditions.

In [16]:
# Filter with multiple conditions

pop_data.query('country == "Spain" & date >= 2000')

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
36,"Population, total",Spain,ESP,2025,NaN,NaN,NaN,0
37,"Population, total",Spain,ESP,2024,48848840.0,NaN,NaN,0
38,"Population, total",Spain,ESP,2023,48352528.0,NaN,NaN,0
39,"Population, total",Spain,ESP,2022,47786102.0,NaN,NaN,0
40,"Population, total",Spain,ESP,2021,47443821.0,NaN,NaN,0
41,"Population, total",Spain,ESP,2020,47359424.0,NaN,NaN,0
42,"Population, total",Spain,ESP,2019,47118501.0,NaN,NaN,0
43,"Population, total",Spain,ESP,2018,46782011.0,NaN,NaN,0
44,"Population, total",Spain,ESP,2017,46571232.0,NaN,NaN,0
45,"Population, total",Spain,ESP,2016,46458139.0,NaN,NaN,0
46,"Population, total",Spain,ESP,2015,46422303.0,NaN,NaN,0
47,"Population, total",Spain,ESP,2014,46460733.0,NaN,NaN,0
48,"Population, total",Spain,ESP,2013,46604197.0,NaN,NaN,0
49,"Population, total",Spain,ESP,2012,46773055.0,NaN,NaN,0
50,"Population, total",Spain,ESP,2011,46742697.0,NaN,NaN,0
51,"Population, total",Spain,ESP,2010,46576897.0,NaN,NaN,0
52,"Population, total",Spain,ESP,2009,46362946.0,NaN,NaN,0
53,"Population, total",Spain,ESP,2008,45954106.0,NaN,NaN,0
54,"Population, total",Spain,ESP,2007,45226803.0,NaN,NaN,0
55,"Population, total",Spain,ESP,2006,44397319.0,NaN,NaN,0
56,"Population, total",Spain,ESP,2005,43653155.0,NaN,NaN,0
57,"Population, total",Spain,ESP,2004,42921895.0,NaN,NaN,0
58,"Population, total",Spain,ESP,2003,42187645.0,NaN,NaN,0
59,"Population, total",Spain,ESP,2002,41431558.0,NaN,NaN,0
60,"Population, total",Spain,ESP,2001,40850412.0,NaN,NaN,0
61,"Population, total",Spain,ESP,2000,40567864.0,NaN,NaN,0

In [18]:
gdp_data.query('countryiso3code == "ITA" & value > 23000')

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
109,GDP per capita (current US$),Italy,ITA,2024,40385.341396,NaN,NaN,1
110,GDP per capita (current US$),Italy,ITA,2023,39277.083878,NaN,NaN,1
111,GDP per capita (current US$),Italy,ITA,2022,35653.904210,NaN,NaN,1
112,GDP per capita (current US$),Italy,ITA,2021,36852.542541,NaN,NaN,1
113,GDP per capita (current US$),Italy,ITA,2020,32091.486662,NaN,NaN,1
114,GDP per capita (current US$),Italy,ITA,2019,33812.788725,NaN,NaN,1
115,GDP per capita (current US$),Italy,ITA,2018,34904.108192,NaN,NaN,1
116,GDP per capita (current US$),Italy,ITA,2017,32844.115661,NaN,NaN,1
117,GDP per capita (current US$),Italy,ITA,2016,31391.569290,NaN,NaN,1
118,GDP per capita (current US$),Italy,ITA,2015,30639.882975,NaN,NaN,1
119,GDP per capita (current US$),Italy,ITA,2014,36028.349402,NaN,NaN,1
120,GDP per capita (current US$),Italy,ITA,2013,35701.674600,NaN,NaN,1
121,GDP per capita (current US$),Italy,ITA,2012,34854.394944,NaN,NaN,1
122,GDP per capita (current US$),Italy,ITA,2011,38432.374282,NaN,NaN,1
123,GDP per capita (current US$),Italy,ITA,2010,35856.862549,NaN,NaN,1
124,GDP per capita (current US$),Italy,ITA,2009,37099.613396,NaN,NaN,1
125,GDP per capita (current US$),Italy,ITA,2008,40828.579558,NaN,NaN,1
126,GDP per capita (current US$),Italy,ITA,2007,37826.175455,NaN,NaN,1
127,GDP per capita (current US$),Italy,ITA,2006,33537.128699,NaN,NaN,1
128,GDP per capita (current US$),Italy,ITA,2005,32062.723834,NaN,NaN,1
129,GDP per capita (current US$),Italy,ITA,2004,31348.190184,NaN,NaN,1
130,GDP per capita (current US$),Italy,ITA,2003,27577.570032,NaN,NaN,1
137,GDP per capita (current US$),Italy,ITA,1996,23122.933722,NaN,NaN,1
141,GDP per capita (current US$),Italy,ITA,1992,23297.046033,NaN,NaN,1

In [28]:
gdp_data.query('date == 2024 | date == 2023')

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
1,GDP per capita (current US$),Germany,DEU,2024,56103.732318,NaN,NaN,1
2,GDP per capita (current US$),Germany,DEU,2023,54776.766824,NaN,NaN,1
37,GDP per capita (current US$),Spain,ESP,2024,35326.768307,NaN,NaN,1
38,GDP per capita (current US$),Spain,ESP,2023,33493.222541,NaN,NaN,1
73,GDP per capita (current US$),France,FRA,2024,46103.084086,NaN,NaN,1
74,GDP per capita (current US$),France,FRA,2023,44700.138418,NaN,NaN,1
109,GDP per capita (current US$),Italy,ITA,2024,40385.341396,NaN,NaN,1
110,GDP per capita (current US$),Italy,ITA,2023,39277.083878,NaN,NaN,1

## 2.4 Filter in a List

Filter rows where column value is in a list.

In [34]:
# Filter Multiple and show unique countries
# You can either do one or two lines

pop_data.query("country in ['Spain', 'Italy']")

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
36,"Population, total",Spain,ESP,2025,NaN,NaN,NaN,0
37,"Population, total",Spain,ESP,2024,48848840.0,NaN,NaN,0
38,"Population, total",Spain,ESP,2023,48352528.0,NaN,NaN,0
39,"Population, total",Spain,ESP,2022,47786102.0,NaN,NaN,0
40,"Population, total",Spain,ESP,2021,47443821.0,NaN,NaN,0
...,...,...,...,...,...,...,...,...
139,"Population, total",Italy,ITA,1994,56843400.0,NaN,NaN,0
140,"Population, total",Italy,ITA,1993,56831821.0,NaN,NaN,0
141,"Population, total",Italy,ITA,1992,56797087.0,NaN,NaN,0
142,"Population, total",Italy,ITA,1991,56758521.0,NaN,NaN,0
143,"Population, total",Italy,ITA,1990,56719240.0,NaN,NaN,0

## 2.5 Select Rows and Columns

Combine row filtering with column selection.

In [33]:
# Filter rows and select columns

# Filter rows and select columns

pop_data.query("country in ['Spain', 'Italy']")[['country', 'date', 'value']]

    country  date       value
36    Spain  2025         NaN
37    Spain  2024  48848840.0
38    Spain  2023  48352528.0
39    Spain  2022  47786102.0
40    Spain  2021  47443821.0
..      ...   ...         ...
139   Italy  1994  56843400.0
140   Italy  1993  56831821.0
141   Italy  1992  56797087.0
142   Italy  1991  56758521.0
143   Italy  1990  56719240.0

[72 rows x 3 columns]

In [ ]:
pop_data.query("country in ['Spain', 'Italy'] & date == 2024")[['country', 'date', 'value']]

KeyError: "['date == 2024'] not in index"

## 2.6 Rename Columns

Rename columns in the dataframe.

In [ ]:
# Before rename
democracy_gdp.head(2)

In [ ]:
# Rename using rename with axis parameter

#YOUR CODE HERE